<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #334155;
            margin: 0;
            padding: 40px;
            background-color: #ffffff;
            font-size: 12px;
        }
        .header {
            border-bottom: 3px solid #1e3a8a;
            padding-bottom: 15px;
            margin-bottom: 25px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
        }
        .header h1 { margin: 0; color: #1e3a8a; font-size: 22px; }
        .header .subtitle { color: #64748b; font-size: 10px; margin-top: 4px; }
        .header .date { color: #64748b; font-size: 10px; text-align: right; }
        
        .section { margin-bottom: 25px; }
        .section-title {
            font-size: 13px; font-weight: bold; color: #0f172a;
            border-left: 4px solid #10b981; padding-left: 8px; margin-bottom: 12px;
            text-transform: uppercase;
        }

        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
        th { background-color: #f1f5f9; color: #475569; font-size: 11px; }
        td { font-size: 12px; }
        
        .highlight-box {
            background-color: #f0fdf4; border: 1px solid #bbf7d0;
            padding: 20px; border-radius: 8px; text-align: center; margin-top: 30px;
        }
        .cost { font-size: 30px; font-weight: bold; color: #047857; margin: 5px 0; }
        .label { font-size: 10px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }

        .footer {
            margin-top: 40px; font-size: 9px; color: #94a3b8; text-align: center;
            border-top: 1px solid #e2e8f0; padding-top: 10px;
        }
    </style>
</head>
<body>

    <div class="header">
        <div>
            <h1>Project Estimation Report</h1>
            <div class="subtitle">Generated by SmartEst AI Engine</div>
        </div>
        <div class="date">Date: {{ $project->created_at->format('M d, Y') }}</div>
    </div>

    <div class="section">
        <div class="section-title">Project Overview</div>
        <table>
            <tr>
                <th width="30%">Project Name</th>
                <td>{{ $project->name }}</td>
            </tr>
            <tr>
                <th>Complexity Level</th>
                <td>{{ ucfirst($project->complexity_level) }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Function Point Analysis (FPA)</div>
        <table>
            <tr>
                <th>Metric</th>
                <th>Value</th>
            </tr>
            <tr>
                <td>Unadjusted Function Points (UFP)</td>
                <td>{{ $project->fpEstimation->ufp ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td>Value Adjustment Factor (VAF)</td>
                <td>{{ $project->fpEstimation->vaf ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td><strong>Adjusted Function Points (AFP)</strong></td>
                <td><strong>{{ $project->fpEstimation->afp ?? 'N/A' }}</strong></td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Effort & Duration Estimation</div>
        <table>
            <tr>
                <th>Parameter</th>
                <th>Estimated Value</th>
            </tr>
            <tr>
                <td>Total Effort</td>
                <td>{{ $project->estimated_effort_hours }} Hours</td>
            </tr>
            <tr>
                <td>Estimated Duration</td>
                <td>{{ $project->estimated_duration_months }} Months</td>
            </tr>
        </table>
    </div>

    <div class="highlight-box">
        <div class="label">Estimated Total Cost</div>
        <div class="cost">${{ number_format($project->estimated_cost, 2) }}</div>
        <div class="label">Based on standard industry hourly rates</div>
    </div>

    <div class="footer">
        This report is auto-generated by SmartEst. The values provided are estimates based on FPA/UCP methodologies and user inputs.
    </div>

</body>
</html>